import { test, expect } from '@playwright/test';
import { open } from './helpers';
const D = '/tmp/claude-0/-home-user-DOOM/a1c8be98-c181-5272-a479-df1c203dea25/scratchpad/shots/';
test('shots plan+run', async ({ page }) => {
  const errs: string[] = [];
  page.on('pageerror', (e) => errs.push(e.message));
  await open(page, '/incidents/INC-0042/plan');
  await expect(page.getByRole('heading', { name: 'Here’s the fix' })).toBeVisible();
  await page.screenshot({ path: D + '01-plan-review.png' });
  await page.getByRole('button', { name: 'Show technical details' }).click();
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.screenshot({ path: D + '02-plan-tech-ack.png' });
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: D + '03-plan-confirm.png' });
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: D + '04-uac-waiting.png' });
  await page.getByRole('button', { name: 'Yes' }).click();
  await expect(page.getByRole('heading', { name: 'Fixed and verified' })).toBeVisible();
  await page.screenshot({ path: D + '05-run-verified.png' });
  expect(errs).toEqual([]);
});
test('shots drift', async ({ page }) => {
  await open(page, '/incidents/INC-0042/plan', { fault: 'drift' });
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await expect(page.getByRole('heading', { name: 'Paused — your PC changed mid-repair' })).toBeVisible();
  await page.screenshot({ path: D + '06-drift.png' });
});
test('shots decline + untrusted + busy', async ({ page }) => {
  await open(page, '/incidents/INC-0042/plan');
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: D + '07-uac-declined.png' });
  await page.keyboard.press('Escape');
  await page.waitForTimeout(200);
  await page.screenshot({ path: D + '07b-declined-inline.png', fullPage: true });
});
test('shots untrusted', async ({ page }) => {
  await open(page, '/incidents/INC-0042/plan', { fault: 'helperUntrusted' });
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.waitForTimeout(500);
  await page.screenshot({ path: D + '08-untrusted.png' });
});
test('shots busy + expired + mismatch', async ({ page }) => {
  await open(page, '/incidents/INC-0042/plan', { fault: 'busy' });
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: D + '09-queued.png' });
  await open(page, '/incidents/INC-0042/plan', { fault: 'expireApproval' });
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.waitForTimeout(300);
  await page.screenshot({ path: D + '10-expired.png' });
  await open(page, '/incidents/INC-0042/plan', { fault: 'mutatePlan' });
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Run the fix' }).click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: D + '11-mismatch.png' });
});
test('shots guided + resume', async ({ page }) => {
  await open(page, '/incidents/INC-0043/guided');
  await expect(page.getByRole('list', { name: 'Guided steps' })).toBeVisible();
  await page.screenshot({ path: D + '12-guided-review.png', fullPage: true });
  await page.getByRole('checkbox', { name: /I understand/ }).check();
  await page.getByRole('button', { name: 'Approve plan' }).click();
  await page.getByRole('button', { name: 'Start guided repair' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await expect(page.getByText(/Progress saved/)).toBeVisible();
  await page.screenshot({ path: D + '13-guided-reboot.png', fullPage: true });
  await page.getByRole('button', { name: 'Restart into Safe Mode' }).click();
  await expect(page.getByRole('heading', { name: /Welcome back/ })).toBeVisible();
  await page.waitForTimeout(80);
  await page.screenshot({ path: D + '14-resume-checking.png' });
  await expect(page.getByRole('button', { name: 'Stop here' })).toBeEnabled();
  await page.screenshot({ path: D + '15-resume-done.png' });
  await page.getByRole('checkbox', { name: /saved my work/ }).check();
  await page.getByRole('button', { name: /Continue/ }).click();
  await expect(page.getByRole('heading', { name: 'Approve this exact plan' })).toBeVisible();
  await page.screenshot({ path: D + '16-continue-plan.png' });
  await page.goto('/?speed=20#/incidents/INC-0043/guided');
  await page.waitForTimeout(800);
  await page.screenshot({ path: D + '17-guided-continuation.png', fullPage: true });
});
test('shots errors', async ({ page }) => {
  await open(page, '/incidents/INC-0039/plan');
  await page.waitForTimeout(500);
  await page.screenshot({ path: D + '18-no-safe-fix.png' });
  await open(page, '/incidents/INC-0041/run');
  await page.waitForTimeout(500);
  await page.screenshot({ path: D + '19-no-run.png' });
});
